### ISSUE TITLE
podcast downloads

### ISSUE THREAD

**Issue by randogoth** [garredow/foxcasts-lite#1]
hey Garrett, really great app, but not of much use to me with a limited data plan. Are there any plans to implement a function to download instead of just being able to stream the episodes?

**Comment by lsjmhar** [comment]
Hi Garrett

Any update on the addition of download facility to the kai os podcast app? Thanks

**Comment by JuanCarlosM1** [comment]
> Hi Garrett
> 
> Any update on the addition of download facility to the kai os podcast app? Thanks

yes the app have updates but you need to build the package, if you want I give you.
